### ISSUE TITLE
Failing to compile on Artix

### ISSUE THREAD

**Issue by avcado** [Hilbis/Hilbish#2]
**Using Artix Linux with Linux 5.11.6**
```
$ go build main.go
# command-line-arguments
./main.go:95:38: undefined: hshprompt
$ echo $?
2
```
Am I missing something?

**Comment by TorchedSammy** [comment]
To compile you have to run `go build` alone, itll bring in everything together
do open a separate issue to remind me to add build instructions on the readme pls thanks
