### ISSUE TITLE
improve readme

### ISSUE THREAD

**Issue by TorchedSammy** [Hilbis/Hilbish#22]
i think that the readme could have more *pizzazz,* including some thing like screenshots, badgets and just make it nicer and more attractive

**Comment by TorchedSammy** [comment]
the problem is that i have no idea what to do

**Comment by marauder316** [comment]
Why don't you take some of the gifs you posted on the r/Unixporn Discord server?

**Comment by TorchedSammy** [comment]
that image is out of date since thats not how the default prompt or config looks anymore
also, can we move this to discussions (#31)
