### ISSUE TITLE
feat: support -n flag

### ISSUE THREAD

**Issue by legendofmiracles** [Hilbis/Hilbish#47]
In most shells there's a `-n` flag for checking syntax, but not executing any of the input the shell gets, e.g. https://media.discordapp.net/attachments/761279800312332328/838790971617312858/unknown.png

Hilbish should also support this, and check all the lua that the user entered (+ maybe the sh input?).

This flag can be used for checking shell scripts for basic syntax errors, without risking to having to run a script.

**Comment by legendofmiracles** [comment]
Whoops, didn't see that you updated it

**Comment by TorchedSammy** [comment]
checking both lua and sh input won't work well (or wouldn't at all)

**Comment by TorchedSammy** [comment]
copy pasting what I said in discord:
hilbish in interactive mode executes lua but if it errors it just runs input as sh
but since with `-n` ur deliberately checking if there's syntax errors having the single switch for both doesn't work
