### ISSUE TITLE
Makefile does not respect DESTDIR

### ISSUE THREAD

**Issue by lmartinez-mirror** [Hilbis/Hilbish#7]
Hi, I'm the AUR maintainer for this package. I believe @MCotocel had asked earlier if I could start building this with the Makefile instead of directly invoking `go build`, however, the Makefile in question doesn't seem to respect whatever DESTDIR is set to. This is important for Arch Linux, as packages are not allowed to directly install to `/usr/bin` without using `pacman`.

This is what I get from an unreleased hilbish PKGBUILD, using the latest release:
```shell
make: Warning: File 'Makefile' has modification time 5828 s in the future
'hilbish' -> '/usr/bin/hilbish'
install: cannot create regular file '/usr/bin/hilbish': Permission denied
make: *** [Makefile:9: install] Error 1
A failure occurred in package().
Aborting...
```

And this is what I have in the PKGBUILD:
```shell
package() {
  cd "$pkgname-$pkgver"
  DESTDIR="$pkgdir/" make install
```

`DESTDIR` is set to `$pkgdir`, which expands to the package directory. So ideally it should install to `$pkgdir/usr/bin/hilbish`

**Comment by lmartinez-mirror** [comment]
Disregard, I'll just patch the Makefile at build-time.

**Comment by JavaCafe01** [comment]
@lmartinez-mirror I can quickly add that officially. I totally forgot to regard the AUR package.

**Comment by TorchedSammy** [comment]
+1, DESTDIR should definitely be used

**Comment by JavaCafe01** [comment]
@lmartinez-mirror I updated in my PR, you should check it out.

**Comment by lmartinez-mirror** [comment]
Hey, thanks so much for the fix! Although the new Makefile raises a new error (because it tries to write to `/etc/shells` without permissions), it's something I can patch out and move to a separate install script to go with the package.
