### ISSUE TITLE
config always overwritten with default

### ISSUE THREAD

**Issue by TorchedSammy** [Hilbis/Hilbish#8]
No matter if Hilbish already has a config in `$HOME`, itll overwrite it with the default config

**Comment by devins2518** [comment]
The file is overwritten [here](https://github.com/Hilbis/Hilbish/blob/master/main.go#L61-67). I think a quick fix would be to check if the file exists, if not create it, if so load it and if there’s any errors either skip the lines or use the default. I’m not well versed in go but someone could easily fix this.
